### PR TITLE
n30f.c: added scaling for images

### PR DESCRIPTION
**Pull request by Accurate0**
Added option -s to scale the image 
Some consistency changes
Small fix to -p

Feel free to make any changes as necessary.

### CODE REVIEW

**Comment by bobertlo** [comment]
I'm not from this project at all but please, one issue per PR! It works out better for everyone :)

**Comment by Accurate0** [comment]
I don't think there any reason for me to make 2 different pull requests for consistency fixes and adding the scaling feature, the changes are very minimalist, and having multiple PRs would be a waste, unless @sdhand disagrees with me.

**Comment by sdhand** [comment]
I agree that in general one issue per PR is better, but seeing as how small the -p fix is I don't see it's worth your time splitting that out into a separate PR now.

However this PR does contain a number of formatting changes (which are arguably needed, I seem to have managed to mix tabs and spaces throughout the code). I'd appreciate these not being included in the PR, as there are several line changes that are not at all to do with the functionality you've added.

Otherwise, looks great, thanks very much!

**Comment by Accurate0** [comment]
I will revert the formatting changes in this PR and submit another PR for those.

**Comment by Accurate0** [comment]
@sdhand I've removed all formatting changes, thanks for the feedback!

Let me know if there's any other changes preventing this from being merged.

**Pull request merged**
